# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1402, 881)
        MainWindow.setStyleSheet("#browser{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"}\n"
"#printer{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"}\n"
"#voice{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"}\n"
"#lights{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"}\n"
"#status{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.voice = QtWidgets.QFrame(self.centralwidget)
        self.voice.setObjectName("voice")
        self.gridLayout.addWidget(self.voice, 1, 1, 1, 1)
        self.status = QtWidgets.QFrame(self.centralwidget)
        self.status.setStyleSheet("")
        self.status.setObjectName("status")
        self.fresh = QtWidgets.QPushButton(self.status)
        self.fresh.setGeometry(QtCore.QRect(130, 320, 93, 28))
        self.fresh.setObjectName("fresh")
        self.printerLabel = QtWidgets.QLabel(self.status)
        self.printerLabel.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.printerLabel.setObjectName("printerLabel")
        self.lightsLabel = QtWidgets.QLabel(self.status)
        self.lightsLabel.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.lightsLabel.setObjectName("lightsLabel")
        self.internetLabel = QtWidgets.QLabel(self.status)
        self.internetLabel.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.internetLabel.setObjectName("internetLabel")
        self.serverLabel = QtWidgets.QLabel(self.status)
        self.serverLabel.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.serverLabel.setObjectName("serverLabel")
        self.printerStatus = QtWidgets.QLabel(self.status)
        self.printerStatus.setGeometry(QtCore.QRect(110, 50, 55, 16))
        self.printerStatus.setObjectName("printerStatus")
        self.lightStatus = QtWidgets.QLabel(self.status)
        self.lightStatus.setGeometry(QtCore.QRect(110, 90, 55, 16))
        self.lightStatus.setObjectName("lightStatus")
        self.internetStatus = QtWidgets.QLabel(self.status)
        self.internetStatus.setGeometry(QtCore.QRect(110, 130, 55, 16))
        self.internetStatus.setObjectName("internetStatus")
        self.serverStatus = QtWidgets.QLabel(self.status)
        self.serverStatus.setGeometry(QtCore.QRect(110, 170, 55, 16))
        self.serverStatus.setObjectName("serverStatus")
        self.gridLayout.addWidget(self.status, 1, 3, 1, 1)
        self.lights = QtWidgets.QFrame(self.centralwidget)
        self.lights.setObjectName("lights")
        self.sing = QtWidgets.QToolButton(self.lights)
        self.sing.setGeometry(QtCore.QRect(50, 70, 93, 28))
        self.sing.setObjectName("sing")
        self.redlight = QtWidgets.QToolButton(self.lights)
        self.redlight.setGeometry(QtCore.QRect(50, 170, 93, 28))
        self.redlight.setObjectName("redlight")
        self.greenlight = QtWidgets.QToolButton(self.lights)
        self.greenlight.setGeometry(QtCore.QRect(50, 270, 93, 28))
        self.greenlight.setObjectName("greenlight")
        self.gridLayout.addWidget(self.lights, 1, 2, 1, 1)
        self.browser = QtWidgets.QFrame(self.centralwidget)
        self.browser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.browser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.browser.setObjectName("browser")
        self.gridLayout.addWidget(self.browser, 0, 1, 1, 2)
        self.printer = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printer.sizePolicy().hasHeightForWidth())
        self.printer.setSizePolicy(sizePolicy)
        self.printer.setObjectName("printer")
        self.formLayout = QtWidgets.QFormLayout(self.printer)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.titleLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleEdit = QtWidgets.QLineEdit(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleEdit.sizePolicy().hasHeightForWidth())
        self.titleEdit.setSizePolicy(sizePolicy)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.typeLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.printType = QtWidgets.QComboBox(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printType.sizePolicy().hasHeightForWidth())
        self.printType.setSizePolicy(sizePolicy)
        self.printType.setObjectName("printType")
        self.printType.addItem("")
        self.printType.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.printType)
        self.boldLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldLabel.sizePolicy().hasHeightForWidth())
        self.boldLabel.setSizePolicy(sizePolicy)
        self.boldLabel.setObjectName("boldLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.boldLabel)
        self.bold = QtWidgets.QCheckBox(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bold.sizePolicy().hasHeightForWidth())
        self.bold.setSizePolicy(sizePolicy)
        self.bold.setObjectName("bold")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bold)
        self.remark = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remark.sizePolicy().hasHeightForWidth())
        self.remark.setSizePolicy(sizePolicy)
        self.remark.setObjectName("remark")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.remark)
        self.remarkEdit = QtWidgets.QLineEdit(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarkEdit.sizePolicy().hasHeightForWidth())
        self.remarkEdit.setSizePolicy(sizePolicy)
        self.remarkEdit.setObjectName("remarkEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.remarkEdit)
        self.context = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context.sizePolicy().hasHeightForWidth())
        self.context.setSizePolicy(sizePolicy)
        self.context.setObjectName("context")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.context)
        self.ContextEdit = QtWidgets.QPlainTextEdit(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContextEdit.sizePolicy().hasHeightForWidth())
        self.ContextEdit.setSizePolicy(sizePolicy)
        self.ContextEdit.setObjectName("ContextEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ContextEdit)
        self.confirm = QtWidgets.QPushButton(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setObjectName("confirm")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.confirm)
        self.gridLayout.addWidget(self.printer, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1402, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "系统"))
        self.fresh.setText(_translate("MainWindow", "刷新"))
        self.printerLabel.setText(_translate("MainWindow", "打印机状态："))
        self.lightsLabel.setText(_translate("MainWindow", "指示灯状态："))
        self.internetLabel.setText(_translate("MainWindow", "网络状态："))
        self.serverLabel.setText(_translate("MainWindow", "服务器状态："))
        self.printerStatus.setText(_translate("MainWindow", "在线"))
        self.lightStatus.setText(_translate("MainWindow", "在线"))
        self.internetStatus.setText(_translate("MainWindow", "在线"))
        self.serverStatus.setText(_translate("MainWindow", "在线"))
        self.sing.setText(_translate("MainWindow", "蜂鸣"))
        self.redlight.setText(_translate("MainWindow", "红灯"))
        self.greenlight.setText(_translate("MainWindow", "绿灯"))
        self.label.setText(_translate("MainWindow", "打印任务"))
        self.titleLabel.setText(_translate("MainWindow", "标题:"))
        self.typeLabel.setText(_translate("MainWindow", "打印类型:"))
        self.printType.setItemText(0, _translate("MainWindow", "单面"))
        self.printType.setItemText(1, _translate("MainWindow", "双面"))
        self.boldLabel.setText(_translate("MainWindow", "是否加粗"))
        self.remark.setText(_translate("MainWindow", "备注:"))
        self.context.setText(_translate("MainWindow", "内容:"))
        self.confirm.setText(_translate("MainWindow", "确认"))


