# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 881)
        MainWindow.setStyleSheet("#photo{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#info{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#video{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#browser{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#printer{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#voice{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#lights{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#status{\n"
                                 "background:#fff;\n"
                                 "border:1px solid #000;\n"
                                 "}\n"
                                 "#redlight{\n"
                                 "background:#cc0000;\n"
                                 "}\n"
                                 "#yellowlight{\n"
                                 "background:#ffff00;\n"
                                 "}\n"
                                 "#greenlight{\n"
                                 "background:#00AA00;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.voice = QtWidgets.QWidget(self.centralwidget)
        self.voice.setObjectName("voice")
        self.gridLayout.addWidget(self.voice, 3, 1, 1, 1)
        self.videoWindow = QtWidgets.QWidget(self.centralwidget)
        self.videoWindow.setObjectName("videoWindow")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.videoWindow)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stotp = QtWidgets.QPushButton(self.videoWindow)
        self.stotp.setObjectName("stotp")
        self.gridLayout_3.addWidget(self.stotp, 1, 2, 1, 1)
        self.start = QtWidgets.QPushButton(self.videoWindow)
        self.start.setObjectName("start")
        self.gridLayout_3.addWidget(self.start, 1, 1, 1, 1)
        self.open = QtWidgets.QPushButton(self.videoWindow)
        self.open.setObjectName("open")
        self.gridLayout_3.addWidget(self.open, 1, 3, 1, 1)
        self.live = QtWidgets.QPushButton(self.videoWindow)
        self.live.setCheckable(True)
        self.live.setObjectName("live")
        self.gridLayout_3.addWidget(self.live, 1, 0, 1, 1)
        self.video = QtWidgets.QLabel(self.videoWindow)
        self.video.setText("")
        self.video.setObjectName("video")
        self.gridLayout_3.addWidget(self.video, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.videoWindow, 1, 3, 2, 2)
        self.browser = QtWidgets.QWidget(self.centralwidget)
        self.browser.setObjectName("browser")
        self.gridLayout.addWidget(self.browser, 0, 1, 3, 2)
        self.printer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printer.sizePolicy().hasHeightForWidth())
        self.printer.setSizePolicy(sizePolicy)
        self.printer.setObjectName("printer")
        self.formLayout = QtWidgets.QFormLayout(self.printer)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.titleLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleEdit = QtWidgets.QLineEdit(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleEdit.sizePolicy().hasHeightForWidth())
        self.titleEdit.setSizePolicy(sizePolicy)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.typeLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.printType = QtWidgets.QComboBox(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printType.sizePolicy().hasHeightForWidth())
        self.printType.setSizePolicy(sizePolicy)
        self.printType.setObjectName("printType")
        self.printType.addItem("")
        self.printType.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.printType)
        self.boldLabel = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldLabel.sizePolicy().hasHeightForWidth())
        self.boldLabel.setSizePolicy(sizePolicy)
        self.boldLabel.setObjectName("boldLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.boldLabel)
        self.bold = QtWidgets.QCheckBox(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bold.sizePolicy().hasHeightForWidth())
        self.bold.setSizePolicy(sizePolicy)
        self.bold.setObjectName("bold")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bold)
        self.remark = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remark.sizePolicy().hasHeightForWidth())
        self.remark.setSizePolicy(sizePolicy)
        self.remark.setObjectName("remark")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.remark)
        self.remarkEdit = QtWidgets.QLineEdit(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarkEdit.sizePolicy().hasHeightForWidth())
        self.remarkEdit.setSizePolicy(sizePolicy)
        self.remarkEdit.setObjectName("remarkEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.remarkEdit)
        self.context = QtWidgets.QLabel(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context.sizePolicy().hasHeightForWidth())
        self.context.setSizePolicy(sizePolicy)
        self.context.setObjectName("context")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.context)
        self.confirm = QtWidgets.QPushButton(self.printer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setObjectName("confirm")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.confirm)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.printer)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.gridLayout.addWidget(self.printer, 3, 2, 1, 1)
        self.status = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setStyleSheet("")
        self.status.setObjectName("status")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.status)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.printerLabel = QtWidgets.QLabel(self.status)
        self.printerLabel.setObjectName("printerLabel")
        self.gridLayout_2.addWidget(self.printerLabel, 0, 0, 1, 1)
        self.printerStatus = QtWidgets.QLabel(self.status)
        self.printerStatus.setObjectName("printerStatus")
        self.gridLayout_2.addWidget(self.printerStatus, 0, 1, 1, 1)
        self.lightsLabel = QtWidgets.QLabel(self.status)
        self.lightsLabel.setObjectName("lightsLabel")
        self.gridLayout_2.addWidget(self.lightsLabel, 1, 0, 1, 1)
        self.lightStatus = QtWidgets.QLabel(self.status)
        self.lightStatus.setObjectName("lightStatus")
        self.gridLayout_2.addWidget(self.lightStatus, 1, 1, 1, 1)
        self.internetLabel = QtWidgets.QLabel(self.status)
        self.internetLabel.setObjectName("internetLabel")
        self.gridLayout_2.addWidget(self.internetLabel, 2, 0, 1, 1)
        self.internetStatus = QtWidgets.QLabel(self.status)
        self.internetStatus.setObjectName("internetStatus")
        self.gridLayout_2.addWidget(self.internetStatus, 2, 1, 1, 1)
        self.serverLabel = QtWidgets.QLabel(self.status)
        self.serverLabel.setObjectName("serverLabel")
        self.gridLayout_2.addWidget(self.serverLabel, 3, 0, 1, 1)
        self.serverStatus = QtWidgets.QLabel(self.status)
        self.serverStatus.setObjectName("serverStatus")
        self.gridLayout_2.addWidget(self.serverStatus, 3, 1, 1, 1)
        self.fresh = QtWidgets.QPushButton(self.status)
        self.fresh.setObjectName("fresh")
        self.gridLayout_2.addWidget(self.fresh, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.status, 3, 4, 1, 1)
        self.lights = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lights.sizePolicy().hasHeightForWidth())
        self.lights.setSizePolicy(sizePolicy)
        self.lights.setObjectName("lights")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lights)
        self.verticalLayout.setObjectName("verticalLayout")
        self.redlight = QtWidgets.QPushButton(self.lights)
        self.redlight.setObjectName("redlight")
        self.verticalLayout.addWidget(self.redlight)
        self.yellowlight = QtWidgets.QPushButton(self.lights)
        self.yellowlight.setObjectName("yellowlight")
        self.verticalLayout.addWidget(self.yellowlight)
        self.greenlight = QtWidgets.QPushButton(self.lights)
        self.greenlight.setObjectName("greenlight")
        self.verticalLayout.addWidget(self.greenlight)
        self.gridLayout.addWidget(self.lights, 3, 3, 1, 1)
        self.photo = QtWidgets.QWidget(self.centralwidget)
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 0, 3, 1, 1)
        self.info = QtWidgets.QWidget(self.centralwidget)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionrecord = QtWidgets.QAction(MainWindow)
        self.actionrecord.setObjectName("actionrecord")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionlive = QtWidgets.QAction(MainWindow)
        self.actionlive.setObjectName("actionlive")
        self.menu.addAction(self.actionlive)
        self.menu.addAction(self.actionrecord)
        self.menu.addAction(self.actionopen)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stotp.setText(_translate("MainWindow", "结束录制"))
        self.start.setText(_translate("MainWindow", "开始录制"))
        self.open.setText(_translate("MainWindow", "打开文件"))
        self.live.setText(_translate("MainWindow", "开启相机"))
        self.label.setText(_translate("MainWindow", "打印任务"))
        self.titleLabel.setText(_translate("MainWindow", "标题:"))
        self.typeLabel.setText(_translate("MainWindow", "打印类型:"))
        self.printType.setItemText(0, _translate("MainWindow", "单面"))
        self.printType.setItemText(1, _translate("MainWindow", "双面"))
        self.boldLabel.setText(_translate("MainWindow", "是否加粗"))
        self.remark.setText(_translate("MainWindow", "备注:"))
        self.context.setText(_translate("MainWindow", "内容:"))
        self.confirm.setText(_translate("MainWindow", "确认"))
        self.printerLabel.setText(_translate("MainWindow", "打印机状态："))
        self.printerStatus.setText(_translate("MainWindow", "在线"))
        self.lightsLabel.setText(_translate("MainWindow", "指示灯状态："))
        self.lightStatus.setText(_translate("MainWindow", "在线"))
        self.internetLabel.setText(_translate("MainWindow", "网络状态："))
        self.internetStatus.setText(_translate("MainWindow", "在线"))
        self.serverLabel.setText(_translate("MainWindow", "服务器状态："))
        self.serverStatus.setText(_translate("MainWindow", "在线"))
        self.fresh.setText(_translate("MainWindow", "刷新"))
        self.redlight.setText(_translate("MainWindow", "红灯"))
        self.yellowlight.setText(_translate("MainWindow", "黄灯"))
        self.greenlight.setText(_translate("MainWindow", "绿灯"))
        self.menu.setTitle(_translate("MainWindow", "视频"))
        self.actionrecord.setText(_translate("MainWindow", "record"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionlive.setText(_translate("MainWindow", "live"))
